import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { useState } from 'react';
import styles from '../styles/Home.module.css'
import Poll from './components/Poll';

const pollQuestion = 'Is react-polls useful?'

const answers = [
  { option: 'Yes', votes: 8 },
  { option: 'No', votes: 2 }
]

type PollVariant = {
  option: string;
  votes: number;
}
  
const Home: NextPage = () => {
  const [pollAnswers, setPollAnswers] = useState<PollVariant[]>(answers);

  function handleVote(voteAnswer: string) {
    const newPollAnswers = pollAnswers.map(answer => {
      if (answer.option === voteAnswer) answer.votes++
      return answer
    })

    setPollAnswers(newPollAnswers)
  }

  return (
    <div className={styles.container}>
      
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Poll question={pollQuestion} answers={answers} onVote={handleVote}/>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
