import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { useState } from 'react';
import styles from '../styles/Home.module.css'
import Poll from './components/Poll';

const pollQuestion = 'What is the next feature SigmaValley should support?'

type PollVariant = {
  option: string;
  votes: number;
}
  
const Home: NextPage = () => {
  const [pollAnswers, setPollAnswers] = useState<PollVariant[]>([
    { option: 'Avatars', votes: 0 },
    { option: 'Deploy NFT models', votes: 0 },
    { option: 'DAO votes', votes: 0 }
  ]);

  function handleVote(voteAnswer: string) {
    const newPollAnswers = (pollAnswers || []).map(answer => {
      if (answer.option === voteAnswer) answer.votes++
      return answer
    })

    setPollAnswers(newPollAnswers)
  }

  return (
    <div className={styles.container}>
      
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Poll question={pollQuestion} answers={pollAnswers} onVote={handleVote}/>
      </main>
    </div>
  )
}

export default Home
